import Head from 'next/head';
import Image from 'next/image';

import Intro from '../components/Intro/Intro';
import SectionContainer from '../components/Layout/SectionContainer';
import About from '../components/About/About';
import Projects from '../components/Projects/Projects';
import Experience from '../components/Experience/Experience';

export default function HomePage() {
  return (
    <div className="container max-w-3xl mx-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col mx-2">
        <Intro />
        <About />
        <Experience />
        <Projects />
      </main>

      <footer className="flex items-center my-4 ">
        <span>Build with</span>
        <a
          href="https://nextjs.org/"
          target="_blank"
          className="px-3 text-[#5d5dd5] italic font-semibold"
          rel="noreferrer"
        >
          NextJS
        </a>
        <span>and</span>
        <a
          href="https://tailwindcss.com/"
          target="_blank"
          className="px-3 text-[#5d5dd5]  italic font-semibold"
          rel="noreferrer"
        >
          Tailwind CSS
        </a>
      </footer>
    </div>
  );
}
